### ISSUE TITLE
How to generate Test & Train path file named "test-prosody.txt" and "train-prosody.txt"?

### ISSUE THREAD

**Issue by RunwuShi** [light1726/SpeechTripleNet#1]
I tried to run the demo speech_editting file and there are some issue about these dataset path files, I wonder the format of these files. Thanks a lot

**Comment by TengNN** [comment]
> I tried to run the demo speech_editting file and there are some issue about these dataset path files, I wonder the format of these files. Thanks a lot

How did you solve the "Test & Train path file" problem? I look forward to hearing from you. Thank you.

**Comment by light1726** [comment]
> > I tried to run the demo speech_editting file and there are some issue about these dataset path files, I wonder the format of these files. Thanks a lot
> 
> How did you solve the "Test & Train path file" problem? I look forward to hearing from you. Thank you.

Hey, they look like the following: 
```
p226_001|p226|/path/to/mels/p226_001.npy|/path/to/lf0s/p226_001.npy|/path/to/energy/p226_001.npy
p226_002|p226|/path/to/mels/p226_002.npy|/path/to/lf0s/p226_002.npy|/path/to/energy/p226_002.npy
p226_003|p226|/path/to/mels/p226_003.npy|/path/to/lf0s/p226_003.npy|/path/to/energy/p226_003.npy
```
